[build-system]
requires = ["setuptools>=75.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "LATENT"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    # ---- JAX / MJX / RL stack
    "jax[cuda12]==0.11.0",
    "mujoco==3.10.0",
    "mujoco-mjx==3.10.0",
    "brax==0.14.2",
    "playground",
    "flax",
    "optax",
    "orbax-checkpoint",
    # ---- support / io / logging
    "numpy",
    "scipy",
    "tyro",
    "ml_collections",
    "wandb",
    "tqdm",
    "absl-py",
    "rich",
    "colorlog",
    "einops",
    "osqp",
    "mediapy",
    "imageio",
    "imageio-ffmpeg",
    "opencv-python",
    "trimesh",
    "huggingface-hub",
    "scikit-learn",
    "hydra-core",
    "matplotlib",
    "pillow",
    "toml",
    "pytz",
    "loop-rate-limiters",
    "tensorflow",
    "tf2onnx",
    "onnxruntime==1.23.2",
    "onnxscript",
]

[tool.setuptools]
packages = ["latent_mj"]

[tool.ruff]
line-length = 120  # You can match black's default
target-version = "py312"  # Adjust to your Python version

[tool.ruff.lint]
select = ["F"]
ignore = ["F401"]
